# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b432a02b17358a13fe118fcf8afaf88fedabd5abd61da1a2519981ab4f7c20c7565643b7d35d05b44e9b067d83869fc59d47db2fa96bb1d5be8fa3f1451bec55

test:
  secret_key_base: a375247fd3119081f27858420cbcd74fe4c19470da6e934da99309de1237ba05b0eceed9ee00fc256af747ad64efc2613d0bb92dcb11750e6b8036592a29ee2e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
